# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chat

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Alamofire', '~> 4.0'
  pod 'AlamofireImage', '~> 3.3'
  pod 'FaceAware', '~> 1.2'
  pod 'FacebookCore'
  pod 'FacebookLogin'

end
